"""
Task 2 -- Feast feature definitions for the IRIS dataset.

- Entity:       iris_id (unique id per tracked iris plant)
- Data source:  the time-series IRIS parquet (event_timestamp + created_timestamp)
- Feature view: the 4 measurements + species, tied to the entity and source

Feast is time-series-first: every feature row needs an event_timestamp so it can
do point-in-time correct joins. The adapted IRIS dataset provides that timestamp.
"""
from datetime import timedelta

from feast import Entity, FeatureView, Field, FileSource, ValueType
from feast.types import Float32, String

# Entity: what each feature row is about
iris = Entity(
    name="iris_id",
    value_type=ValueType.INT64,
    description="Unique identifier for each tracked iris plant",
)

# Data source: the time-series parquet (generated by prepare_data.py)
iris_source = FileSource(
    name="iris_source",
    path="data/iris.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created_timestamp",
)

# Feature view: groups the iris features under the entity + source
iris_fv = FeatureView(
    name="iris_features",
    entities=[iris],
    ttl=timedelta(days=3650),   # long TTL so materialized values stay servable
    schema=[
        Field(name="sepal_length", dtype=Float32),
        Field(name="sepal_width", dtype=Float32),
        Field(name="petal_length", dtype=Float32),
        Field(name="petal_width", dtype=Float32),
        Field(name="species", dtype=String),
    ],
    source=iris_source,
    online=True,
)
